data: data/allMeSH_2022.json
output_dir: output/pubmedbert_fast
min_label_count: 100
val_split: 0.1
test_split: 0.1

model_name: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext
max_length: 256
batch_size: 32

epochs: 30
early_stopping_patience: 5
warmup_ratio: 0.1
lr: 2.0e-5
dropout: 0.1
